---
title: "Lab 02 - Plastic waste"
author: "Truc (Tina) Le"
date: "01/30/22"
output: html_document
---

## Load packages and data

```{r setup, message=FALSE}
# Load the tidyverse package
library(tidyverse)
```

```{r load-data, message=FALSE}
plastic_waste <- read_csv(here::here("C:/Users/tinal/Documents/GitHub/ProgDataClass/data/plastic-waste.csv"))
```

## Exercises

### Exercise 1

Remove this text, and add your answer for Exercise 1 here.

```{r plastic-waste-continent}
#histogram 
ggplot(data = plastic_waste)+
  aes(x = plastic_waste_per_cap) +
  geom_histogram(binwidth = .5)+
  facet_wrap(~continent)
#density
ggplot(data = plastic_waste)+
  aes(x = plastic_waste_per_cap) +
  facet_wrap(~continent)+
  geom_density(aes(y = after_stat(count)))
#history and density
ggplot(data = plastic_waste)+
  aes(x = plastic_waste_per_cap) +
  geom_histogram(binwidth = .5)+
  facet_wrap(~continent)+
  geom_density(aes(y = after_stat(count)))
 
  
```

### Exercise 2

```{r plastic-waste-density}
# insert code here
```

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r plastic-waste-violin}
# insert code here
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r plastic-waste-mismanaged}
# insert code here
```

### Exercise 6
