---
title: "lab-04-green-reputation"
author: "Truc Le"
date: "3/23/2022"
output: html_document
---

```{r package}
library(tidyverse)

```


```{r data files}

dictionary <- readr::read_csv(here::here("GitHub",  "ProgDataClass","data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("Github","ProgDataClass","data", "green_data.csv"))

``` 

``` {Question 1}
##Inspect the item responses (e.g., with graphs or by summarizing distinct values). Is anything unusual?

green_data|>
  select(-id)|>
  unlist()|>
  unique()

green_data <- green_data|>
  mutate(
    across(
      -id,
      \(x) recode(x, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "-99" = NA_real_)
    )
  )

#I found the value of -99 and recoded it to be NA.

```

``` {Question 2}
##Compute total scores for the four scales. Recode variables as needed.


green_data<- green_data |>
  rowwise()|>
  mutate(
    green_total = mean(c_across(green1:green5), na.rm = TRUE),
    comp_total = mean( c_across(comp1:comp10), na.rm = TRUE),
    intel_total = mean ( c_across(intel1:intel10), na.rm = TRUE),
    open_total = mean( c_across(open1:open10), na.rm = TRUE),
  .after = id
  )|>
  ungroup()
##compute total scores

reversed <- dictionary |>
  filter (Keying == -1)|>
  pull(Item)

green_data <- green_data|>
  mutate( 
    across (
      all_of(reversed), 
      \(x) recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1)
    )
  )
#recoded the variables

```

``` {Question 3}
##Rescale the variables so that they go from 0-100 instead of the original range. Name the rescaled variables *_pomp.

green_data<- green_data |>
  mutate( 
    across(
      green_total:open_total,
        \(x) 100 * (x - 1) / (5 - 1),
      .names = "{.col}_pomp"
    ),
    .after = open_total
    )

#I don't know why this is showing an error, big sad :(
green_data <- green_data |>
  mutate(
    across(
      green_total:open_total,
      \(x) datawizard:: changescale(x, range = c(1,5), to c(0,100))
    )
  )
```

```{Question 4}
##Make plots that illustrate the distributions of the 4 POMP-scored variables.

#histogram
ggplot(green_data)+
  aes(x = green_total_pomp)+
  geom_histogram()

#scatterplot with line trend
ggplot(green_data)+
  aes(x = open_total_pomp, y = green_total_pomp, color = factor(student))+
  geom_point()+
  geom_smooth()
 

